### PR TITLE
Use original results spreadsheet

### PR DESCRIPTION
**Pull request by sumeetadur**
To avoid data duplication and confusion about which sheet to update

### CODE REVIEW

**Comment by callumlocke** [comment]
can you change it so it does the two Bertha requests in parallel?

``` js
const [contentRes, resultsRes] = await Promise.all([fetch(contentURL), fetch(resultsURL)]);
```

**Comment by sumeetadur** [comment]
Good spot! I've changed that now.

**Comment by callumlocke** [comment]
👍

**Comment by callumlocke** [comment]
and can you delete the options from the spreadsheet if they're not being used any more

**Comment by sumeetadur** [comment]
Done 👍

**Pull request merged**
